project:
  type: website
  output-dir: docs

website:
  title: "Grace M. Horne"
  navbar:
    left:
      - research.qmd
      - outreach.qmd
      - resources.qmd
    right:
      - icon: github
        href: https://github.com/gracehorne
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/ghorneworm
        aria-label: Twitter

format:
  html:
    theme: litera
    css: styles.css
    toc: true



