project:
  type: website
  output-dir: docs

website:
  title: "Grace M. Horne"
  text-align: center
  sidebar:
    tools:
      - icon: github
        href: https://github.com/gracehorne
        aria-label: GitHub
      - icon: twitter
        href: https://twitter.com/ghorneworm
        aria-label: Twitter
      - icon: mastodon
        href: https://mastodon.social/@gracehorne
        aria-label: Mastodon
    title: "Grace M. Horne"
    style: "floating"
    search: true
    contents:
      - text: "Research"
        file: research.qmd
      - text: "Outreach"
        file: outreach.qmd
      - text: "Resources"
        file: resources.qmd

format:
  html:
    page-layout: full
    anchor-sections: false
    theme: 
      - styles.css
      - simplex
    mainfont: "Avenir Next"
    toc: true    



