project:
  type: website
  output-dir: docs

website:
  title: "Grace M. Horne"
  navbar:
    left:
      - research.qmd
      - outreach.qmd
      - resources.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



